/* MIS2 장비로 이전에 따른 HOMEDIR 경로 수정.    2004.05.  DSA2000
*/
/*#define		HOMEDIR				"/edi/new"*/
#define		HOMEDIR				"/hper/insa/HINSA/proc/src/EDIsrc"
#define		DATADIR				"DATA"
#define		SND				"SND"
#define		SNT				"SNT"
#define		RCV				"RCV"
#define		IP				"203.233.124.56"
#define		PORT				2212	  	/*SKB 운영  Port */
#define 	TRX_CODE			"         "
#define		MAGICLINKID			"BK01495 "	/*SKB 운영 발신자ID 20byte*/
#define		PASSWORD			"0923    "	  /*SKB 운영 passwd    8byte*/
/*#define		MAGICLINKID			"HE01495 "	SKB 테스트 발신자ID 20byte*/
/*#define		PASSWORD			"1111    "	  SKB 테스트 passwd    8byte*/

#define		DEFAULT_COCODE		"AL"
#define		DEFAULT_DATACODE	"ALL"
#define		DEFAULT_RFLAG		'E'

#define		DATA_SIZE			2048	

#define		ALARM				300
#define		FILEFLAG			0
#define		FILEAPPFLAG			1	
#define		DIRFLAG				2	
